name: Bug Report
description: Report a bug in the project
title: "[bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: "## 🐛 Bug Report\nPlease fill out the details below to help us resolve your issue quickly."

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide a step-by-step guide of the actions you took that led to the bug."
      placeholder: |
        1. Open the plugin
        2. Select a text layer
        3. Reorder the layer.
        4. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen."
      placeholder: "The code should be generated successfully and displayed in the output panel."
    validations:
      required: false

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happened. Include any error messages or logs if applicable."
      placeholder: "An error message appears: 'Failed to generate code due to invalid layer configuration.'"
    validations:
      required: false

  - type: input
    id: design-link
    attributes:
      label: "Design Reference"
      description: "If applicable, provide a link to the design related to this bug (e.g., Figma link)."
      placeholder: "e.g., https://www.figma.com/file/example"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots or Videos"
      description: "If applicable, add screenshots or provide links to videos to help explain the issue. You can drag and drop images here or paste them from your clipboard."
      placeholder: "Drag and drop images or videos here"
    validations:
      required: false
      placeholder: "Drag and drop images or videos here fix"
